[package]
name = "rustionnaire"
version = "0.1.0"
authors = ["kopps <simon.kopp@thi.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
